kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - npm install
    - npm run-script build
- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: build/