kind: pipeline
name: default

steps:
- name: build
  image: node
  commands:
    - npm install
    - npm build
    - mkdir /drone
    - mkdir /drone/src
    - cp build /drone/src
- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: build/